### ISSUE TITLE
Replace tables with a more advanced component

### ISSUE THREAD

**Issue by calixteman** [mozilla/bugzilla-dashboard#109]
They have a lot of nice features and it will avoid to reinvent the wheel.

**Comment by sylvestre** [comment]
@helfi92 do you have an opinion on this? Thanks

**Comment by helfi92** [comment]
`bugzilla-dashboard` uses the material instead of bootstrap for it's overall theme. For advanced usage of tables, I would recommend considering

* [mui-datatables](https://github.com/gregnb/mui-datatables)
* [material-table](https://material-table.com)

both of which are [recommended](https://material-ui.com/components/tables/#complementary-projects) by the material-ui team.

**Comment by sylvestre** [comment]
Done!
