### ISSUE TITLE
Bug in code for putting bugs into buckets

### ISSUE THREAD

**Issue by armenzg** [mozilla/bugzilla-dashboard#32]
In the utils directory I have some code to group bugs into weekly buckets using Friday as the cutover day.

I was running the tests late at night and I noticed that there was an intermittent test failure.
There's some issues either on the code or the tests where sometimes the datetimes are handled as UTC and sometimes as local timezone.
This means that even though I run the tests on a Tuesday; the temporary UTC "today" variable is on Wednesday which caused a failure.

Here's a commit that explains this a bit better:
```diff
- it('Current - To Friday of current week', () => {
+ it('Current - To default day of the week of current week', () => {
   const newDate = toDayOfWeek();
-  const myTempDate = new Date();
-  const distance = 5 - myTempDate.getDay(); // 5 represents Friday
-  myTempDate.setDate(myTempDate.getDate() + distance);
+  // If Toronto's datetime is 2019-01-22 10:24pm then
+  // myTempDate is 2019-01-23T03:24:36.156Z
+  // getDay() would return 2 while getUTCDay() returns 3
+  const myTempDate = new Date(); // UTC
+  const distance = 5 - myTempDate.getUTCDay(); // 5 represents Friday
+  myTempDate.setDate(myTempDate.getUTCDate() + distance);
   expect(newDate).toBe((myTempDate).toISOString().split('T')[0]);
 });
```
I don't think this is a huge problem (some bugs may be counted on different weeks), however, it will be good to be fixed if it itches someone.

I'm marking it as good first issue and let someone give it a try.

**Comment by shadxx7** [comment]
Hey @armenzg , I'd like to work on this issue, if that's okay?

**Comment by shadxx7** [comment]
The problem is that the Date() API creates a date object with the current UTC time, where as when the same object is passed into moment its converted to the local timezone, so when ever the local time zone has moved to the next day and UTC is behind, one of the tests fail. 

A fix would be to use moment to create the dates instead of the Date() API, which would keep everything consistent. I can send a PR as soon as @eperelman confirms whether Pacific time or UTC is to be used.

**Comment by armenzg** [comment]
Thank you for your help!
